#!/usr/bin/env ruby

# Some more information can be found under
# http://wiki.eclipse.org/Equinox/p2/Ant_Tasks#Repo2Runnable
# http://help.eclipse.org/galileo/index.jsp?topic=/org.eclipse.platform.doc.isv/guide/p2_repositorytasks.htm
require "rexml/document"
include REXML
require 'optparse'
module ElipsePlatform

  private
    @@slicingOptions = {
      'includeOptional' => 'true',
      'includeNonGreedy' => 'false',
  #    'followOnlyFilteredRequirements' => 'true',
      'followStrict' => 'true',
    }
    NameOfAntFile    = 'buildTargetPlatform.xml'

  public
    def ElipsePlatform::eclipseTarget2antFile(targetRoot, eclipsetarget, antFile = NameOfAntFile)
      defaultAntTarget = 'buildTargetPlatform'
      doc = Document.new File.new(eclipsetarget) # input
      p2def = Document.new # output
      proj = Element.new "project"
      proj.attributes['name'] = defaultAntTarget
      p2def.add_element proj
      target = nil
      doc.elements.each("target") {
	|element|
	target = Element.new('target')
	target.attributes['name']=defaultAntTarget
	proj.attributes['default']=defaultAntTarget
	element.elements.each('locations/location') do
	  |srcLocation|
	    trace "location: #{srcLocation} \n   #{srcLocation.attributes['id']} #{srcLocation.attributes['version']}"
	    p2mirror = Element.new('p2.mirror')
	    slicing = Element.new('slicingOptions')
	    @@slicingOptions.each { |x, y | slicing.attributes[x]=y }
	    p2mirror.add_element(slicing)
	    if /delta/i.match(srcLocation.attributes['path']) && /directory/i.match(srcLocation.attributes['type'])
	      info "Setup: Patching DELTA-path from #{srcLocation.attributes['path']} => #{DELTA_DEST}"
	      srcLocation.attributes['path'] = DELTA_DEST
	    end
	    case srcLocation.attributes['type']
		when 'InstallableUnit'
		  p2mirror.attributes['source'] =  srcLocation.elements['repository'].attributes['location']
		when 'Directory'
		  p2mirror.attributes['source'] =  srcLocation.attributes['path']
		else
		  puts "Don't know how to handle location of type other than Directory or InstallableUnit. Was:"; p srcLocation
		  exit 2
	    end
	    artifact = Element.new('destination')
	    artifact.attributes['location'] = "file://#{targetRoot}"
	    artifact.attributes['name'] = "Target repository generated by #{__FILE__} using #{eclipsetarget}"
	    p2mirror.add_element(artifact)
	    srcLocation.elements.each('unit') do |unit|
	      iu = Element.new('iu')
	      ['id', 'version'].each {|attr| iu.attributes[attr] = unit.attributes[attr] }
	      p2mirror.add_element(iu)
	    end
	    target.add_element(p2mirror)
	  end
      }
      proj.add_element target

      p2def << XMLDecl.new
      p2def.write( $stdout, 0 ) if $VERBOSE
      File.open(antFile, 'w') {|f| p2def.write(f, 0 ) }
      info  "Transformed target definition #{eclipsetarget} into ant script for p2 #{antFile}"
    end

    def ElipsePlatform::generate(targetRoot, targetDefinition, p2_exe)
      eclipseTarget2antFile(targetRoot, targetDefinition, NameOfAntFile)
      NameOfAntFile
      cmd = "java -jar #{p2_exe}/plugins/org.eclipse.equinox.launcher_*.jar " +
      "-application org.eclipse.ant.core.antRunner "+
      "#{$VERBOSE ? '-verbose' : ''} " +
	  " -verbose -compare -ignoreErrors " +
      "-f #{NameOfAntFile}"
      info "Create targetPlatform in #{targetRoot} as defined by #{targetDefinition}. Using ant file #{NameOfAntFile}"
      info cmd
      res = system(cmd)
    end
end