#!/bin/sh
export ChooseBranch=2.1.6
./gen_repo.rb --branch $ChooseBranch .
./prepareJenkins.rb --branch $ChooseBranch
cd elexis-base/BuildElexis
ant -Dos=linux.x86_64 linux.x86_64 -Dskip_texify=false
#ant -Dos=macosx clean macosx
#ant -Dos=linux linux doc doc-plugins javadoc
#ant -Dos=windows windows
#ant -Dos=macosx macosx
